enum MASS_STORAGE_SUBCLASS_CODES
{
	SCSI_BUS_CONTROLLER = 0x00,
	IDE_CONTROLLER,
	FLOPPY_DISK_CONTROLLER,
	IPI_BUS_CONTROLLER,
	RAID_CONTROLLER,
	ATA_CONTROLLER,
	SERIAL_ATA,
	SERIAL_ATTACHED_SCSI,
	OTHER = 0x80
};